name: continuous-deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # We are building an ARM template rather than submitting the Bicep directly
  # because this allows us to use the latest version of the Bicep compiler.

  build-armtemplate:
    uses: ./.github/workflows/build-armtemplate.yml

  validate-infrastructure:
    needs:
      - build-armtemplate
    uses: ./.github/workflows/validate-infrastructure.yml
    with:
      LOCATION: ${{ vars.LOCATION }}
      BASE_RESOURCE_NAME: ${{ vars.BASE_RESOURCE_NAME }}
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      APPSERVICEPLAN_CONFIGURATION: ${{ vars.APPSERVICEPLAN_CONFIGURATION }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  
  deploy-infrastructure:
    needs:
      - validate-infrastructure
    uses: ./.github/workflows/deploy-infrastructure.yml
    with:
      LOCATION: ${{ vars.LOCATION }}
      BASE_RESOURCE_NAME: ${{ vars.BASE_RESOURCE_NAME }}
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      APPSERVICEPLAN_CONFIGURATION: ${{ vars.APPSERVICEPLAN_CONFIGURATION }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

  test-dmcserver:
    uses: ./.github/workflows/test-dmcserver.yml

  build-dmcserver:
    needs:
      - test-dmcserver
    uses: ./.github/workflows/build-dmcserver.yml
  
  publish-dmcserver:
    needs:
      - build-dmcserver
      - deploy-infrastructure
    uses: ./.github/workflows/publish-dmcserver.yml
    with:
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      WEBAPPNAME: ${{ needs.deploy-infrastructure.outputs.WEBAPPNAME }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    