name: lint-bicep

on:
  workflow_call:

jobs:
  lint-bicep:
    name: Lint Bicep
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Bicep
      run: | 
        curl -Lo bicepinstall https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicepinstall
        sudo mv ./bicepinstall /usr/local/bin/bicep
        bicep --help
     
    - name: Lint Bicep
      run: |
        bicep build ./infrastructure/bicep/main.bicep